### PR TITLE
Add .travis.yml (WIP?)

### PR DESCRIPTION
**Pull request by gus-massa**
I copied the `.travis.yml` file and made the obvious changes. A similar script works in my machine but I get an error in travis [compatibility/#L667-L670](https://travis-ci.org/gus-massa/compatibility/builds/544816867#L667-L670). 

    raco setup: 1 making: <pkgs>/net-test/tests/net
    instantiate: unknown module
      module name: #<resolved-module-path:"/home/travis/racket/collects/syntax/moddep.rkt">
      compilation context...:

It is strange because I can see the file `moddep.rkt`. I tried a few changes, but I was no able to fix this. 

I probably need some help from @samth here.

### CODE REVIEW

**Comment by mflatt** [comment]
I worry that it's a concurrency problem in `raco setup`. Does the error go away if you add `-j 1` to `raco setup`?

**Comment by samth** [comment]
I added that so we'll see.

**Comment by gus-massa** [comment]
Installing with setup `racket-test` before the main part that install the `compatibility-test` fix the problem, but I don't understand the details here.

I removed the `-j 1` because it was no necessary, made a tiny change in the formatting of the `ls` and fixed a silly typo in the last test. I also commented the part about `xvfb`. Is it necessary in this repo?

**Comment by samth** [comment]
I don't think `xvfb` is needed for these tests. I don't understand why that change fixed the moddep problem though.

**Comment by samth** [comment]
I merged this since we believe it to be working, and having tests is better than not.

**Pull request merged**
